/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#872000",
        "border-light": "#E5E5E5",
        "surface-container-low": "#f4f3f1",
        "inverse-surface": "#2f312f",
        "honey-gold": "#F4A100",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1a",
        "inverse-primary": "#ffb3b3",
        "success-mint": "#2ECC71",
        "slate-dark": "#121212",
        "primary-fixed": "#ffdad9",
        "on-tertiary-container": "#fff9f7",
        "coral-red": "#F75A5A",
        "surface-tint": "#bf002e",
        "background": "#faf9f6",
        "on-secondary-fixed": "#221b00",
        "secondary-fixed-dim": "#e9c400",
        "secondary": "#705d00",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#920021",
        "on-background": "#1a1c1a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-container": "#fcd400",
        "surface-container": "#efeeeb",
        "on-secondary-fixed-variant": "#544600",
        "on-secondary": "#ffffff",
        "surface": "#faf9f6",
        "surface-variant": "#e3e2e0",
        "on-surface-variant": "#5d3f3f",
        "secondary-fixed": "#ffe16d",
        "inverse-on-surface": "#f2f1ee",
        "tertiary-container": "#d63800",
        "surface-bright": "#faf9f6",
        "on-primary-container": "#fff9f8",
        "tertiary": "#aa2b00",
        "surface-dim": "#dbdad7",
        "surface-container-high": "#e9e8e5",
        "error-container": "#ffdad6",
        "deep-indigo": "#1E006A",
        "outline-variant": "#e7bcbc",
        "on-primary-fixed": "#400009",
        "surface-container-highest": "#e3e2e0",
        "card-dark": "#1C1C1E",
        "on-secondary-container": "#6e5c00",
        "outline": "#926e6e",
        "tertiary-fixed": "#ffdbd1",
        "tertiary-fixed-dim": "#ffb5a0",
        "primary": "#e6003a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb3b3",
        "on-tertiary-fixed": "#3b0900",
        "primary-container": "#e6003a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "16px",
        "md": "12px",
        "sm": "8px",
        "base": "4px",
        "lg": "16px",
        "xxxl": "32px",
        "xxl": "24px",
        "gutter": "12px",
        "xs": "4px",
        "xl": "20px"
      },
      fontFamily: {
        "body-md": ["DM Sans", "sans-serif"],
        "headline-lg": ["Hammersmith One", "sans-serif"],
        "title-sm": ["DM Sans", "sans-serif"],
        "label-caps": ["DM Sans", "sans-serif"],
        "headline-md": ["Hammersmith One", "sans-serif"],
        "caption": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "title-sm": ["18px", {"lineHeight": "24px", "fontWeight": "500"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "caption": ["10px", {"lineHeight": "14px", "fontWeight": "600"}],
        "body-lg": ["15px", {"lineHeight": "22px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
